### ISSUE TITLE
"ValueError: too many values to unpack" when triggering builds

### ISSUE THREAD

**Issue by upsuper** [mozilla/mozilla_ci_tools#420]
```text
$ mozci-trigger -r 2dec9c12a438 --times 20 -b "Ubuntu VM 12.04 try debug test mochitest-6" --debug
01/18/2016 06:13:58 root INFO:   Setting DEBUG level
01/18/2016 06:13:58 mozci DEBUG:         Determine if the user's credentials are valid.
01/18/2016 06:13:58 mozci DEBUG:         Loading LDAP user from c:/Users/upsuper/.mozilla/mozci/credentials.cfg
01/18/2016 06:13:58 requests.packages.urllib3.connectionpool INFO:       Starting new HTTPS connection (1): secure.pub.build.mozilla.org
01/18/2016 06:13:59 requests.packages.urllib3.connectionpool DEBUG:      "GET /buildapi/self-serve HTTP/1.1" 200 2167
01/18/2016 06:13:59 mozci DEBUG:         Loading c:/Users/upsuper/.mozilla/mozci/repositories.txt
01/18/2016 06:13:59 requests.packages.urllib3.connectionpool INFO:       Starting new HTTPS connection (1): secure.pub.build.mozilla.org
01/18/2016 06:14:00 requests.packages.urllib3.connectionpool DEBUG:      "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
01/18/2016 06:14:01 mozci DEBUG:         Determine repository associated to try
01/18/2016 06:14:01 mozci DEBUG:         Determine repository associated to try
01/18/2016 06:14:01 mozci DEBUG:         About to fetch https://hg.mozilla.org/try/json-pushes?changeset=2dec9c12a438&tipsonly=1
01/18/2016 06:14:01 requests.packages.urllib3.connectionpool INFO:       Starting new HTTPS connection (1): hg.mozilla.org
01/18/2016 06:14:03 requests.packages.urllib3.connectionpool DEBUG:      "GET /try/json-pushes?changeset=2dec9c12a438&tipsonly=1 HTTP/1.1" 200 None
01/18/2016 06:14:03 mozci DEBUG:         Push info: {u'date': 1453092337, u'changesets': [u'2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a'], u'user': u'xquan@mozilla.com', 'pushid': u'104926'}
01/18/2016 06:14:03 root INFO:   https://treeherder.mozilla.org/#/jobs?repo=try&revision=2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a
01/18/2016 06:14:03 mozci DEBUG:         Determine repository associated to try
01/18/2016 06:14:03 mozci INFO:  We want to have 20 job(s) of Ubuntu VM 12.04 try debug test mochitest-6 on revisions [u'2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a']
01/18/2016 06:14:03 mozci INFO:
01/18/2016 06:14:03 mozci INFO:  === 2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a ===
01/18/2016 06:14:03 mozci DEBUG:         Determine if the revision is valid.
01/18/2016 06:14:03 requests.packages.urllib3.connectionpool INFO:       Starting new HTTPS connection (1): hg.mozilla.org
01/18/2016 06:14:04 requests.packages.urllib3.connectionpool DEBUG:      "GET /try/json-pushes?changeset=2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a&tipsonly=1 HTTP/1.1" 200 None
01/18/2016 06:14:04 mozci INFO:  We want to have 20 job(s) of Ubuntu VM 12.04 try debug test mochitest-6 on revision 2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a
01/18/2016 06:14:04 mozci DEBUG:         Find jobs matching 'Ubuntu VM 12.04 try debug test mochitest-6'
01/18/2016 06:14:04 buildapi_client DEBUG:       About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/try/rev/2dec9c12a438bd4a2f28639ec7cbc320f3b7a63a?format=json
01/18/2016 06:14:04 root ERROR:  too many values to unpack
Traceback (most recent call last):
  File "c:\mozilla-build\python\lib\site-packages\mozci\scripts\trigger.py", line 391, in main
    trigger_build_if_missing=options.trigger_build_if_missing
  File "c:\mozilla-build\python\lib\site-packages\mozci\mozci.py", line 452, in trigger_range
    matching_jobs = QUERY_SOURCE.get_matching_jobs(repo_name, rev, buildername)
  File "c:\mozilla-build\python\lib\site-packages\mozci\query_jobs.py", line 136, in get_matching_jobs
    all_jobs = self.get_all_jobs(repo_name, revision)
  File "c:\mozilla-build\python\lib\site-packages\mozci\query_jobs.py", line 121, in get_all_jobs
    query_jobs_schedule(repo_name, revision, auth=get_credentials())
  File "c:\mozilla-build\python\lib\site-packages\buildapi_client\buildapi_client.py", line 212, in query_jobs_schedule
    req = requests.get(url, auth)
  File "c:\mozilla-build\python\lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "c:\mozilla-build\python\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\mozilla-build\python\lib\site-packages\requests\sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "c:\mozilla-build\python\lib\site-packages\requests\sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "c:\mozilla-build\python\lib\site-packages\requests\models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "c:\mozilla-build\python\lib\site-packages\requests\models.py", line 391, in prepare_url
    enc_params = self._encode_params(params)
  File "c:\mozilla-build\python\lib\site-packages\requests\models.py", line 89, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack
```

**Comment by armenzg** [comment]
This worked for me:
python mozci/scripts/trigger.py -r 2dec9c12a438 --times 20 -b "Ubuntu VM 12.04 try debug test mochitest-6" --debug --dry-run
