### ISSUE TITLE
Calling buildbot_graph_builder with incorrect builders should not fail

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#423]
I'm adding to pulse_actions discarding invalid builders in order to not fail when calling buildbot_graph_builder().

Mozci should handle this more gracefully.
```
python -c "from mozci.sources.buildbot_bridge import buildbot_graph_builder; buildbot_graph_builder(['try builder'], revision='60bf93213cdd')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mozci/sources/buildbot_bridge.py", line 164, in buildbot_graph_builder
    if is_downstream(b):
  File "mozci/platforms.py", line 55, in is_downstream
    return get_buildername_metadata(buildername)['downstream']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by armenzg** [comment]
Fixed in https://github.com/mozilla/mozilla_ci_tools/commit/11b33da120b1f49afc36fc5c7a65875d75e27a5e
