### ISSUE TITLE
Make trigger_missing_jobs not fail on build jobs

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#502]
I think it thinks Thunderbird builds are test jobs.

TODO:
* change signature for explicit test on empty files (I don't like the current implementation)
* write test

Oct 09 19:01:42 pulse-actions app/worker1.1: mozci	 INFO:	 ==> We want to trigger 'TB Rev7 MacOSX Yosemite 10.10.5 try-comm-central debug test mozmill' a total of 1 time(s). 
Oct 09 19:01:42 pulse-actions app/worker1.1: mozci	 INFO:	  
Oct 09 19:01:42 pulse-actions app/worker1.1: mozci	 INFO:	 We will trigger 1) 'TB OS X 10.7 64-bit try-comm-central leak test build' 
Oct 09 19:01:42 pulse-actions app/worker1.1: mozci	 INFO:	 instead of 2) 'TB Rev7 MacOSX Yosemite 10.10.5 try-comm-central debug test mozmill' 
Oct 09 19:01:42 pulse-actions app/worker1.1: mozci	 INFO:	 We need to trigger the build job once (1) in order to be able to run the test job (2). 
Oct 09 19:01:42 pulse-actions app/worker1.1: mozci	 INFO:	 After (1) is done and if no coalesccing happens the test jobs associated with it will be triggered. 
Oct 09 19:01:43 pulse-actions app/worker1.1: root	 ERROR:	 The handler failed to do is job. We will mark the job as failed 
Oct 09 19:01:43 pulse-actions app/worker1.1: Traceback (most recent call last): 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "pulse_actions/worker.py", line 370, in route 
Oct 09 19:01:43 pulse-actions app/worker1.1:     revision=revision, **kwargs) 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "/app/pulse_actions/handlers/treeherder_push_action.py", line 49, in on_event 
Oct 09 19:01:43 pulse-actions app/worker1.1:     mgr.trigger_missing_jobs_for_revision(repo_name, revision, dry_run=dry_run) 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/ci_manager.py", line 116, in trigger_missing_jobs_for_revision 
Oct 09 19:01:43 pulse-actions app/worker1.1:     trigger_build_if_missing=trigger_build_if_missing 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 556, in trigger_range 
Oct 09 19:01:43 pulse-actions app/worker1.1:     trigger_build_if_missing=trigger_build_if_missing) 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 470, in trigger_job 
Oct 09 19:01:43 pulse-actions app/worker1.1:     extra_properties=extra_properties 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 582, in trigger 
Oct 09 19:01:43 pulse-actions app/worker1.1:     extra_properties=extra_properties) 
Oct 09 19:01:43 pulse-actions app/worker1.1:   File "/app/.heroku/python/lib/python2.7/site-packages/buildapi_client/buildapi_client.py", line 63, in trigger_arbitrary_job 
Oct 09 19:01:43 pulse-actions app/worker1.1:     raise BuildapiError("The variable files was empty, please try again.") 
Oct 09 19:01:43 pulse-actions app/worker1.1: BuildapiError: The variable files was empty, please try again.

**Comment by armenzg** [comment]
This happened with:
- TB OS X 10.7 64-bit try-comm-central leak test build
- WINNT 5.2 autoland leak test spidermonkey_tier_1-plaindebug build

**Comment by armenzg** [comment]
Fixed with:
https://github.com/mozilla/mozilla_ci_tools/commit/35007f57cd3fea1d57f1226dc1f3dcf5d27574b5
https://github.com/armenzg/buildapi_client/commit/342385fa50f60302a3492f949b23ddc437b2f487
